import { findFirefoxRdpPort, RDP } from "./firefox-rdp.js";
import { setTimeout as wait } from "node:timers/promises";
const port = findFirefoxRdpPort();
const rdp = new RDP(port!);
await rdp.connect();
const res = await rdp.request("root", "listTabs");
const yt = (res.tabs as {url?:string,actor:string}[]).find(t => t.url?.includes("youtube.com/watch"));
const target = await rdp.request(yt!.actor, "getTarget");
const ca = (target.frame as {consoleActor:string}).consoleActor;
await rdp.request(ca, "startListeners", { listeners: ["PageError", "ConsoleAPI"] });
console.log("Subscribed. Waiting 45s for logs...");
await wait(45_000);
const msgs = await rdp.request(ca, "getCachedMessages", { messageTypes: ["ConsoleAPI"] });
const all = (msgs.messages || []) as {arguments?: {value: string}[]}[];
const ytdl = all.filter(m => (m.arguments?.[0]?.value ?? "").includes("ytdl:"));
console.log(`Found ${ytdl.length} ytdl messages:`);
ytdl.forEach(m => console.log("  " + (m.arguments?.[0]?.value ?? "")));
rdp.destroy();
